-- additional_repo_inserts.sql
-- Additional repos: 23
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'TeglonLabs', 'mathpix-gem', 'TeglonLabs/mathpix-gem', 'Ruby', 2, 0, 11, '2026-01-01T12:13:13Z', 'Transform mathematical images to LaTeX');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'TeglonLabs', 'coin-flip-mcp', 'TeglonLabs/coin-flip-mcp', 'JavaScript', 0, 2, 1, '2025-09-21T08:57:27Z', 'MCP server for flipping coins with varying degrees of randomness from random.org');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'TeglonLabs', 'monad-mcp-server', 'TeglonLabs/monad-mcp-server', NULL, 0, 0, 0, '2025-05-14T11:36:14Z', 'Monad MCP Server');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'TeglonLabs', 'topoi', 'TeglonLabs/topoi', 'Python', 0, 0, 1, '2025-01-24T04:49:26Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'kaggle_ncaa18', 'DJedamski/kaggle_ncaa18', 'Jupyter Notebook', 0, 0, 0, '2018-03-07T12:36:09Z', 'Code for NCAA March Madness competition (2018)');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'Project_Euler', 'DJedamski/Project_Euler', NULL, 0, 0, 0, '2015-10-14T02:10:45Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'EDA', 'DJedamski/EDA', 'R', 0, 0, 0, '2014-11-09T16:51:34Z', 'Coursera Project');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'Kaggle', 'DJedamski/Kaggle', NULL, 1, 0, 0, '2014-11-03T02:22:01Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'Getting-and-Cleaning-Data', 'DJedamski/Getting-and-Cleaning-Data', 'R', 1, 0, 0, '2014-10-26T20:53:14Z', 'Coursera Project');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'DJedamski', 'School', 'DJedamski/School', 'R', 1, 1, 0, '2014-10-09T02:55:13Z', 'A couple small projects from grad school');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'kristinezheng', 'kristinezheng.github.io', 'kristinezheng/kristinezheng.github.io', 'HTML', 0, 0, 0, '2026-05-14T22:28:57Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'kristinezheng', 'lookit-jenga', 'kristinezheng/lookit-jenga', 'Jupyter Notebook', 0, 0, 0, '2024-05-16T18:29:01Z', 'Lookit study for 9.85');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'kristinezheng', 'auditory-illusion', 'kristinezheng/auditory-illusion', 'CSS', 0, 0, 0, '2022-03-11T19:22:33Z', '9.35 spring 2022 auditory illusion');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'kristinezheng', 'graph_example', 'kristinezheng/graph_example', 'Python', 0, 0, 0, '2021-10-08T07:29:51Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'kristinezheng', 'Green-Machine', 'kristinezheng/Green-Machine', 'Python', 0, 0, 0, '2021-09-19T05:33:01Z', 'HackMIT 2021: Sustainability Track');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'M1shaaa', 'M1shaaa/M1shaaa', NULL, 0, 0, 0, '2026-06-06T02:49:18Z', 'Config files for my GitHub profile.');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'lab-bookshelf-', 'M1shaaa/lab-bookshelf-', 'TypeScript', 0, 0, 0, '2024-12-31T05:11:14Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'rosie-s-study-3-lookit-project', 'M1shaaa/rosie-s-study-3-lookit-project', NULL, 0, 0, 0, '2024-11-04T22:15:35Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'Python-Lookit-Uploads', 'M1shaaa/Python-Lookit-Uploads', 'Python', 0, 0, 0, '2024-02-16T15:20:50Z', 'random projects');
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'Classes', 'M1shaaa/Classes', NULL, 0, 0, 0, '2023-12-07T08:16:20Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'Yale-Work', 'M1shaaa/Yale-Work', 'HTML', 0, 0, 0, '2023-12-06T18:33:10Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'MNIST-Classifier', 'M1shaaa/MNIST-Classifier', NULL, 0, 0, 0, '2023-11-28T06:12:13Z', NULL);
INSERT INTO repo_snapshots (id, increment_id, org_or_user, repo_name, full_name, language, stars, forks, open_issues, pushed_at, description) VALUES (nextval('repo_seq'), 1, 'M1shaaa', 'Lookit-Demo', 'M1shaaa/Lookit-Demo', NULL, 0, 0, 0, '2023-04-10T02:50:03Z', NULL);